project:
  type: website
  output-dir: docs

website:
  site-url: https://xia071212.github.io/myrepo/
  title: "Yuting Xia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bio.qmd
      - resume.qmd
      - blog/index.qmd
  page-footer:
    center: |
      © 2026 Yuting Xia
    left: |
      ![](/images/UniversityofPennsylvania_FullLogo_RGB.png){width=100px}

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    lang: en
    html-math-method: mathml
